name: CI-CD try

on: [push]

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - name: install packages 📦
        uses: actions/cache@v2.1.7
      - run: npm i 
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: build
      uses: actions/setup-node@v2
    - run: npm run build

  test:
    runs-on: ubuntu-latest

    needs: [install-node-modules,build]
    steps:
      - name: test
        uses: actions/setup-node@v2.4.1
      - run: npm run test 
  
  run:
    runs-on: ubuntu-latest

    needs: [install-node-modules,build]
    steps:
      - name: test
        uses: actions/setup-node@v2.4.1
      - run: npm run start