name: "CI-CD try"

on: [push]

jobs:
  install-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2.1.7
        env:
          cache-name: "cacahe-1"
        with:
          path: |
            ~/.npm
            "node_modules/**"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: install packages 📦
        uses: actions/setup-node@v2
      - run: npm i

  build:
    runs-on: ubuntu-latest
    needs: [install-node-modules]
    steps:
      # - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v2
      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [install-node-modules]
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: actions/setup-node@v2.4.1
      - run: npm run test

  run:
    runs-on: ubuntu-latest

    needs: [install-node-modules]
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: actions/setup-node@v2.4.1
      - run: npm run start
